name: Auto Configure CloudFlareIPlus

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  configure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up permissions
      run: |
        chmod +x CFIPlus.sh

    - name: Install Git and configure user
      run: |
        sudo apt-get update
        sudo apt-get install -y git
        git config --global user.email "your_email@example.com"
        git config --global user.name "Your Name"

    - name: Run CFIPlus.sh
      run: |
        if [ -n "$1" ]; then
          ./CFIPlus.sh "$1"
        else
          ./CFIPlus.sh
        fi

    - name: Commit changes if any
      run: |
        if git status --porcelain | grep -qE '^[MADRCU].'; then
          git add.
          git commit -m "Auto configuration changes"
          git push origin main
        else
          echo "No changes to commit."
        fi
