name: Auto Configure CloudFlareIPlus

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  configure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up permissions
      run: |
        chmod +x CFIPlus.sh

    - name: Run CFIPlus.sh
      run: |
        if [ -n "$1" ]; then
           ./CFIPlus.sh "$1"
        else
           ./CFIPlus.sh
        fi
