name: Run Scripts

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up permissions
      run: |
        chmod +x jh.sh
        chmod +x CFIPlus.sh
        chmod +x speed_AIO.sh

    - name: Install modules
      run: |
        # 根据实际情况安装所需模块
        pip install required_module

    - name: Run jh.sh
      run:./jh.sh

    - name: Run CFIPlus.sh
      run:./CFIPlus.sh

    - name: Run speed_AIO.sh
      run:./speed_AIO.sh
