name: Run Scripts

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up permissions
      run: |
        chmod +x CFIPlus.sh
        chmod +x speed_AIO.sh

    - name: Update and install shell commands
      run: |
        sudo apt update
        sudo apt install -y bash-completion # 示例安装一个常见的 shell 命令工具，你可以根据需要添加更多命令安装步骤

    - name: Run CFIPlus.sh
      run:./CFIPlus.sh

    - name: Run speed_AIO.sh
      run:./speed_AIO.sh
